version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - build/mysql.config
    ports:
      - "3306:3306"

  sharepass:
    build: .
    env_file:
      - build/dev.config
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor

volumes:
  ? mysqldata
  ? vendor