version: "3"
services:
  mysql:
    image: mysql:8.0
    env_file:
      - build/mysql.config
    ports:
      - "3306:3306"

  php:
    build: .
    env_file:
      - build/dev.config
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - .:/var/www/html
